name: Log Time Job

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  log_time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run logging script
        run: |
          chmod +x log_time.sh
          ./log_time.sh

      - name: Run count logs script
        run: |
          chmod +x count_logs.sh
          ./count_logs.sh

      - name: Commit and push changes
        run: |
          git config --global user.name "joaquintamayo"
          git config --global user.email "tamayojoaquinelijah@gmail.com"
          git add log.txt log_count.txt
          git commit -m "Update log files with new timestamp and count" || echo "No changes to commit"
          git push
